// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hktfpxmzhmgfznhvsogg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrdGZweG16aG1nZnpuaHZzb2dnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNjkzMTUsImV4cCI6MjA2Mjk0NTMxNX0.MAV6wOrZqxV1BVOavUDojkxtDmkPF-BS6pvemQGeJH4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);